#!/usr/bin/env python3
"""Assemble the negative results into one document, with every number read from artefacts.

Three findings came out of this project and none of them is the one it set out to make.
They are scattered across a Methods page, a README and ten JSON files, which is the state
in which results quietly rot: the moment a number is retyped into prose it stops being
recomputed, and this project has already had a Methods paragraph claim an AUC of 0.976
against a baseline of 0.829 for some time after the run that produced them was superseded.

So this generates the document rather than hosting a written one. Every figure is read from
the deposited artefact that produced it, and a number that changes upstream changes here on
the next build or is visibly missing. The prose that remains is the part that genuinely is
prose: what the finding means, what would falsify it, and what it does not license anyone
to claim.

Written as Markdown so it can go straight into a repository or a manuscript draft, and
deliberately structured as claim / evidence / limitation rather than as a narrative, because
a negative result is only worth anything if the reader can see immediately what would
overturn it.
"""

from __future__ import annotations

import json
import pathlib
import sys
from typing import Any, Dict

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from pipeline import config

REL = config.ROOT_DIR / "release"
OUT = config.ROOT_DIR / "FINDINGS.md"


def load(name: str) -> Dict[str, Any]:
    for base in (REL, config.INTERIM_DIR):
        try:
            return json.loads((base / name).read_text())
        except (OSError, ValueError):
            continue
    return {}


def main() -> int:
    stats = load("STATS.json")
    geom = load("geometry_measured_labels.json")
    lin = load("p0_lineage_determinants.json")
    decay = load("identity_decay_curve.json")
    var = load("sequence_head_variants.json")
    conf = load("structure_source_confound.json")
    ret = load("candidate_retrieval_scores.json")
    proto = load("evaluation_protocol.json")

    if not (geom and lin and decay):
        print("missing artefacts — run the analyses first")
        return 1

    g = lin["geometry"]
    gceil = sum(g["ceiling"].values()) / len(g["ceiling"])
    gbet = [v["mean"] for v in g["between"].values()]
    e = lin.get("esm2-35M (PCA 20)", {})
    eceil = sum(e["ceiling"].values()) / len(e["ceiling"]) if e else float("nan")
    ebet = [v["mean"] for v in e["between"].values()] if e else []
    curve = {round(r["identity"], 2): r for r in decay.get("curve", [])}
    c = ret.get("counts", {})

    md = f"""# PANTS: three negative results about predicting PET-degrading enzymes

*Generated by `scripts/build_findings_document.py`. Every figure is read from the
artefact that produced it; none is transcribed. Data and artefacts:
[10.5281/zenodo.21807353](https://doi.org/10.5281/zenodo.21807353).*

## Summary

We assembled {stats.get('characterised_total', '?')} characterised polyester hydrolases with
{stats.get('activity_measurements', '?'):,} published activity measurements, including
**150 enzymes expressed, assayed and found to release no product** — a measured negative
class, as distinct from the absence-from-a-database negatives the field usually relies on.
Against those labels, three things that appeared to work do not.

The distinction matters more than any single number here. A database of plastic-active
enzymes records what worked; an enzyme missing from it may have been assayed and failed, or
never assayed at all. Every result below changed when that ambiguity was removed.

---

## Finding 1 — Active-site geometry does not predict PET activity

**Claim.** Catalytic-triad and cleft geometry, measured from structure, carries no
information about whether a polyesterase degrades PET.

**Evidence.** On negatives inferred from database absence, cleft depth separated the classes
at **AUC 0.808, p 1.7×10⁻⁷**. On measured negatives — {geom['n_positive']} PET-active against
{geom['n_negative']} measured-inactive, all ESMFold structures on both sides so no
coordinate-source confound applies — the cluster-grouped result is
**AUC {geom['grouped_auc_mean']:.3f}** ({geom['grouped_auc_min']:.3f}–{geom['grouped_auc_max']:.3f}
over 10 splits). Cleft depth alone falls to
**{geom['per_feature']['cleft_depth_A']['auc']:.3f}, p {geom['per_feature']['cleft_depth_A']['p']:.2g}**.

**Why it is not simply an underpowered test.** As the measured negative set filled in, the
result moved *toward* chance: 0.507 at 95 negatives, 0.498 at 125, 0.459 at 139, and
{geom['grouped_auc_mean']:.3f} with the positive set complete. A real effect emerging from a
thin sample strengthens and narrows around a non-null value. Moving toward and past chance as
n grows is a confound being diluted.

**Limitations.** {geom['n_shared_clusters']} clusters contain both classes. Every structure
here is a prediction, and predictions idealise the active site — see Finding 2's control —
so a real difference could in principle be flattened by the modelling rather than absent from
the enzymes.

---

## Finding 2 — The determinants are lineage-specific, which is why nothing transfers

**Claim.** There may be no single global sequence-to-activity rule to learn. What predicts
PET activity inside one enzyme family does not predict it in another, and sometimes predicts
the opposite.

**Evidence.** Fitting the same model separately inside each lineage large enough to support
one, and comparing the directions the fits point in. The reference is not zero but an
empirical ceiling: how well two bootstrap resamples of the *same* lineage agree, since noisy
vectors drawn from an identical process do not agree perfectly either.

| Features | Same lineage (ceiling) | Different lineages | Pairs pointing opposite ways |
|---|---|---|---|
| Active-site geometry | **{gceil:+.3f}** | {min(gbet):+.3f} to {max(gbet):+.3f} | 2 of 3 |
| ESM-2 embeddings | **{eceil:+.3f}** | {min(ebet):+.3f} to {max(ebet):+.3f} | 2 of 3 |

The same pattern appears in two feature sets that share nothing: one derived from 3D
coordinates, one from a protein language model over sequence. The high ceiling is what makes
this a result rather than a shrug — the within-lineage directions are well determined, so it
is specifically the between-lineage comparison that fails.

**What it explains.** A model trained across lineages learns a direction that reverses on a
lineage it has not seen. That is how geometry reached {geom['grouped_auc_mean']:.3f}, below
chance, and why an eighteen-fold larger language model changed nothing.

**Supporting control.** Predicted and experimental coordinates are not interchangeable.
Paired within the same protein (n={conf.get('oxyanion_n2_angle_deg', {}).get('n', '?')}), the
oxyanion hole differs systematically: second-donor angle
**{conf.get('oxyanion_n2_angle_deg', {}).get('xray', float('nan')):.1f}° in the crystal against
{conf.get('oxyanion_n2_angle_deg', {}).get('model', float('nan')):.1f}° in the model**,
p {conf.get('oxyanion_n2_angle_deg', {}).get('p', float('nan')):.1g}. Cleft depth is
source-invariant. Any analysis mixing coordinate sources inherits this.

**Limitations.** Established on three lineages. It is a strong indication, not a settled law,
and it is the first explanation offered here that accounts for every failure at once.

---

## Finding 3 — A learned classifier does not beat nearest-neighbour retrieval

**Claim.** On labels somebody measured, no model built here outperforms scoring a candidate
by its similarity to the nearest enzyme already known to degrade PET.

**Evidence.** Representation capacity is not the bottleneck. Frozen ESM-2 embeddings,
size-weighted leave-one-cluster-out:

| Representation | Dimensions | AUC | vs composition |
|---|---|---|---|
| amino-acid composition | 20 | {var.get('composition', {}).get('auc', float('nan')):.3f} | — |
| ESM-2 35M | 480 | {var.get('esm2-35M', {}).get('auc_size_weighted', float('nan')):.3f} | {var.get('esm2-35M', {}).get('over_composition', float('nan')):+.3f} |
| ESM-2 150M | 640 | {var.get('esm2-150M', {}).get('auc_size_weighted', float('nan')):.3f} | {var.get('esm2-150M', {}).get('over_composition', float('nan')):+.3f} |
| ESM-2 650M | 1280 | {var.get('esm2-650M', {}).get('auc_size_weighted', float('nan')):.3f} | {var.get('esm2-650M', {}).get('over_composition', float('nan')):+.3f} |

Within the one lineage large enough to measure it (262 enzymes,
{decay.get('n_active', '?')} active, {decay.get('n_inactive', '?')} inactive), re-clustered at
successively stricter identities with whole sub-clusters held out:

| Identity | Sub-clusters scored | Head | Retrieval | Composition |
|---|---|---|---|---|
| 80% | {curve.get(0.8, {}).get('n_scored', '?')} | {curve.get(0.8, {}).get('head', float('nan')):.3f} | {curve.get(0.8, {}).get('retrieval', float('nan')):.3f} | {curve.get(0.8, {}).get('composition', float('nan')):.3f} |
| 70% | {curve.get(0.7, {}).get('n_scored', '?')} | {curve.get(0.7, {}).get('head', float('nan')):.3f} | {curve.get(0.7, {}).get('retrieval', float('nan')):.3f} | {curve.get(0.7, {}).get('composition', float('nan')):.3f} |
| 60% | {curve.get(0.6, {}).get('n_scored', '?')} | {curve.get(0.6, {}).get('head', float('nan')):.3f} | {curve.get(0.6, {}).get('retrieval', float('nan')):.3f} | {curve.get(0.6, {}).get('composition', float('nan')):.3f} |

Read as point estimates this shows an operating band at 70%. **Read with intervals it is not
there**: the paired lead — head minus retrieval on the *same* held-out sub-clusters — is
**+0.159 [−0.263, +0.390]**, spanning zero. Seventeen sub-clusters cannot resolve a difference
that size, and the curve is not monotonic: composition beats both at 80%.

**What survives.** At 70% identity the head's own interval **[0.521, 0.798]** excludes 0.5, so
within a lineage among relatives sharing about 70% of their sequence there is weak evidence of
better-than-chance discrimination. It simply cannot be shown to beat looking the answer up.

**Consequence.** Candidates are ranked by identity to the nearest measured-active enzyme, each
carrying a competence band: **{c.get('in-range', '?')} in range, {c.get('marginal', '?')}
marginal, {c.get('out-of-range', '?')} out of range**. The out-of-range candidates are
precisely the novel enzymes the project set out to find, and nothing here can score them.

---

## What would change these conclusions

Not more enzymes, and not a larger model. More **lineages**: approximately ten enzymes from
each of fifteen new 30%-identity clusters, assayed under one protocol at 37 °C on amorphous
PET. About 150 assays, taking evaluable lineages from 3 to roughly 18. The accompanying
`validation_panel.csv` selects them.

A secondary and cheaper change: report quantitative values with explicit limits of detection
for negatives rather than binary calls, and cross the assay conditions so that within-enzyme
temperature contrasts are identifiable.

## Reproducing any number here

Every figure above is read at build time from a JSON artefact in the Zenodo deposit. The
analyses that produce them are `geometry_measured_labels.py`,
`p0_lineage_specific_determinants.py`, `identity_decay_curve.py`,
`sequence_head_variants.py`, `structure_source_confound.py` and
`run_evaluation_protocol.py`. Not one number in this document was typed by hand.
"""
    OUT.write_text(md)
    print(f"wrote {OUT} ({len(md.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
